name: GitHub Push To Main Actions For Nats Server Runner
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: "RELEASE"
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - run: echo -e "PUSH/MERGE to main"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test
      - name: Publish
        if: ${{ success() }}
        run: ./gradlew -i sign publishToSonatype closeAndReleaseSonatypeStagingRepository
